### ISSUE TITLE
Make up throws error

### ISSUE THREAD

**Issue by nsorros** [MantisAI/prodigy-service#1]
`make up` for the prodigy service in Overton throws
```
mkdir -p /prodigy
cat prodigy.json.template | envsubst > /prodigy/prodigy.json
/bin/sh: 1: cannot create /prodigy/prodigy.json: Permission denied
make: *** [Makefile:20: /prodigy/prodigy.json] Error 2
```

**Comment by nsorros** [comment]
possibly related with the `env` variable `prodigy_home` being set up to `/prodigy` instead of `prodigy`. @ivyleavedtoadflax can confirm

**Comment by ivyleavedtoadflax** [comment]
Yes could be, in which case you should check what permissions are set on `/prodigy`. 

Note that `/prodigy` is not an mistake. Setting prodigy home to this ensures that that the location on the instance and in the container are the same, so that when you pass a prodigy command you can use the same paths. If you set it to `./prodigy` things get more complicated.

**Comment by ivyleavedtoadflax** [comment]
Thinking about this more, `/prodigy` will be created when the volume is mounted so the user will be `root`, so we can either add `sudo` to the `make up` command, or pre-create the `/prodigy` folder in the Makefile using the `ubuntu` or `1001` user.
